---
ID: "787dff86-1414-4260-9d94-830646318d97"
Parent: "bd372d9d-6e4f-4ae9-a54c-dbc2acdebe2a"
Template: "bd372d9d-6e4f-4ae9-a54c-dbc2acdebe2a"
Path: "/sitecore/templates/Project/click-click-launch/Components/Promos/AnimatedPromo/__Standard Values"
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{A053ED9F-4099-4682-9411-2B4C98E481E4}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "96ab1418-d345-473a-950d-05c88c48662c"
Languages:
- Language: en
  Versions:
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250214T165012Z
    - ID: "3a2a1142-68ca-4f5b-afb0-c17d2c0ef8ea"
      Hint: secondaryLink
      Value: |
        <link text="Secondary Link CTA" linktype="external" url="https://www.sitecore.com" anchor="" target="" />
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "84a2a397-786e-43bd-85a0-bfbcc51fc3f3"
      Hint: image
      Value: |
        <image mediaid="{865E1E26-2CF0-4ADC-86CF-0FC3D0A76658}" alt="Electric Car" />
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9dcb454c-83dd-423d-907d-5a0e93b08eda"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "c00d4bd2-a452-4067-a861-e8c6d47201a7"
      Hint: description
      Value: This is a description field and can be longer for more information.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250807T134018Z
    - ID: "da7db0f2-08eb-47c5-af07-ed12a1e998db"
      Hint: title
      Value: Animated Promo Title
    - ID: "e9e9c847-e0f0-497d-8e41-5211a087029a"
      Hint: primaryLink
      Value: |
        <link text="Primary Link CTA" linktype="external" url="https://sitecore.ai" anchor="" target="" />
